import { deviceType, osName } from "react-device-detect";

export const identities = [
  {
    key: "alpha@example.com",
    email: "alpha@example.com",
    name: "Alpha",
    country: "United States",
    custom: {
      region: "America",
      city: "Chicago",
      premium: false,
      staff: true,
      device: deviceType,
      operatingSystem: osName,
    },
  },
  {
    key: "bravo@example.com",
    email: "bravo@example.com",
    name: "Bravo",
    country: "Norway",
    custom: {
      region: "Europe",
      city: "Oslo",
      premium: true,
      staff: false,
      device: deviceType,
      operatingSystem: osName,
    },
  },
  {
    key: "charlie@example.com",
    email: "charlie@example.com",
    name: "Charlie",
    country: "United Kingdom",
    custom: {
      region: "Europe",
      city: "London",
      premium: false,
      staff: false,
      device: deviceType,
      operatingSystem: osName,
    },
  },
  {
    key: "delta@example.com",
    email: "delta@example.com",
    name: "Delta",
    country: "Singapore",
    custom: {
      region: "Asia",
      city: "Singapore",
      premium: true,
      staff: false,
      device: deviceType,
      operatingSystem: osName,
    },
  },
  {
    key: "echo@example.com",
    email: "echo@example.com",
    name: "Echo",
    country: "United States",
    custom: {
      region: "America",
      city: "Oakland",
      premium: true,
      staff: false,
      device: deviceType,
      operatingSystem: osName,
    },
  },
  {
    key: "foxtrot@example.com",
    email: "foxtrot@example.com",
    name: "Foxtrot",
    country: "Australia",
    custom: {
      region: "Australia",
      city: "Sydney",
      premium: false,
      staff: true,
      device: deviceType,
      operatingSystem: osName,
    },
  },
];
